---
name: "tiller"
version: "0.10.0"
usage: "Please see https://github.com/jcstanaway/helm-tiller for usage"
description: "Start a Tiller server locally, aka Tillerless Helm"
command: "$HELM_PLUGIN_DIR/scripts/tiller.sh"
useTunnel: false
